### ISSUE TITLE
Add a hook for deep cloning

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-simple-resource#11]
Not everyone will be OK with shallow cloning. We should expose a hook for supplying a custom function, per resource, so that folks can deep clone if they need it.

**Comment by sprjr** [comment]
How would you envision this working now that we've removed the overrides and are instead suggesting you fire different actions? Would this be possible to do instead without too much headache?

```
const books = createResource('books');
const {reducers, actionTypes: {RETRIEVE_MANY_BOOKS}} = books;

books.addTypeReducers([
  {actionType: MY_ACTION_TYPE, reducer(state,action) => {
    // in this case, we _kind of_ want the default behavior, but we also want to deepClone
    const default = reducers[RETRIEVE_MANY_BOOKS];
    return _.cloneDeep(default(state, action);
  }}
]);
```

Granted, that would clone the *whole* state but, they could also just do that for a specific location or object. (e.g., if they just retrieved a single resource, they could deep clone that and re-insert it instead of doing the whole list).

Then, when they want extended behavior on the default, they have a way to do it. Is that too complex of an approach compared to what you're thinking with the hook? Do we even need that if they have that control in the action creators?

**Comment by jmeas** [comment]
I was thinking a lower level hook here, like...

```js
import {setClone} from 'redux-simple-resource';

// Configure the lib to use a custom clone
setClone(a => _.deepClone(a));
```

The default would be:

```js
clone(a) {
  return {...a};
}
```

Then, anywhere in the code where we might choose to spread to shallow clone, we would instead call `clone()`.

It's sort of like if a lib says that they use native Promises unless you want to use your own Promise library. They usually let you override the constructor somewhere. The solution you proposed seems like they'd be like:

"If you want to use your own promise, override each method that this library provides and wrap it in your own promise"

so I'm leanin' more toward the lower level solution (if we even ever add anything like this). What do you think?

**Comment by jmeas** [comment]
@sprjr talked about this a bit offline. One concern he had is that deep cloning everywhere could lead to performance problems, which makes a lot of sense. So a low-level hook to support that may lead folks astray. The APIs he was suggesting would support deep cloning sometimes, which could possibly help people?

Neither of us would use this feature, so what I think we should do is close this issue out and wait until someone in the community needs different behavior. Then, we can design an API to solve their use case, rather than try to come up with use cases that we don't have.

**Comment by jmeas** [comment]
Cool. Gonna close as revisit.
